#!/usr/bin/env python3
"""Generate the static Cloudflare Pages site from verified inventory and page copy."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).parent
PUBLIC = ROOT / "public"
DOMAIN = "https://www.banyantrees.org"
PHONE = "727-644-9200"
TEL = "+17276449200"
inventory = json.loads((ROOT / "data/inventory.json").read_text())

NAV = [
    ("Young Trees", "/young-banyan-trees/"),
    ("Specimen Trees", "/specimen-trees/"),
    ("For Professionals", "/for-professionals/"),
    ("Care Guide", "/banyan-tree-care-tampa-bay/"),
    ("Our Approach", "/our-approach/"),
]

def button(label, href, style="solid", extra=""):
    return f'<a class="button button--{style} {extra}" href="{href}">{label}<span aria-hidden="true">↗</span></a>'

def kicker(text):
    return f'<p class="eyebrow">{text}</p>'

def section_head(label, heading, body=""):
    return f'{kicker(label)}<h2>{heading}</h2>' + (f'<p class="lead">{body}</p>' if body else '')

def image(alt, cls="", lazy=True):
    return f'<img class="{cls}" src="/assets/banyan-tree-urban-farm-1200.webp" srcset="/assets/banyan-tree-urban-farm-800.webp 800w, /assets/banyan-tree-urban-farm-1200.webp 1200w" sizes="(max-width: 760px) 100vw, 60vw" width="1200" height="800" alt="{alt}" {"loading=lazy" if lazy else "fetchpriority=high"}>'

def band(label, title, text, cta="Call to discuss your tree", href=f"tel:{TEL}"):
    return f'''<section class="contact-band"><div class="wrap contact-band__inner"><div>{kicker(label)}<h2>{title}</h2><p>{text}</p></div>{button(cta, href, "light")}</div></section>'''

def layout(title, description, path, content, page_class="", schema=""):
    url = DOMAIN + path
    nav = ''.join(f'<a href="{href}" {"aria-current=page" if href == path else ""}>{label}</a>' for label, href in NAV)
    crumbs = '' if path == '/' else f'<nav class="breadcrumbs wrap" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>{escape(title.split(" | ")[0])}</span></nav>'
    org = {"@context":"https://schema.org","@type":"Organization","name":"The Banyan Tree Company","url":DOMAIN+"/","telephone":"+1-727-644-9200","areaServed":["St. Petersburg, Florida","Tampa, Florida","Clearwater, Florida","Sarasota, Florida"]}
    structured = json.dumps(org, ensure_ascii=False).replace("<", "\\u003c")
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | The Banyan Tree Company</title><meta name="description" content="{escape(description, quote=True)}">
<meta name="theme-color" content="#18231D"><meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="{url}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/site.css?v=2"><script src="/assets/site.js?v=2" defer></script>
<meta property="og:type" content="website"><meta property="og:site_name" content="The Banyan Tree Company"><meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{DOMAIN}/assets/banyan-tree-company-og.jpg"><meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{structured}</script>{schema}</head>
<body class="{page_class}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap site-header__inner"><a class="brand" href="/" aria-label="The Banyan Tree Company home"><span class="brand__mark" aria-hidden="true">✳</span><span class="brand__text">THE BANYAN<br>TREE COMPANY</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">☰</span></button><nav class="site-nav" id="site-nav" aria-label="Main navigation">{nav}<a class="nav-cta" href="/consultation/">Start a Conversation <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main">{crumbs}{content}</main>
<footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand brand--footer" href="/"><span class="brand__mark" aria-hidden="true">✳</span><span class="brand__text">THE BANYAN<br>TREE COMPANY</span></a><p>A living landmark for the landscape.<br>St. Petersburg · Tampa Bay · Gulf Coast</p></div><nav aria-label="Footer navigation"><a href="/young-banyan-trees/">Young Trees</a><a href="/specimen-trees/">Specimen Trees</a><a href="/for-professionals/">For Professionals</a><a href="/banyan-tree-care-tampa-bay/">Care Guide</a></nav><div class="footer-contact"><span class="eyebrow">START A CONVERSATION</span><a class="footer-phone" href="tel:{TEL}">{PHONE}</a><a href="/consultation/">Prepare a project brief ↗</a></div></div><div class="wrap footer-bottom"><span>© 2026 The Banyan Tree Company</span><span><a href="/privacy/">Privacy</a> · <a href="/sitemap.xml">Sitemap</a></span></div></footer>
<a class="mobile-call" href="tel:{TEL}">Call {PHONE} <span aria-hidden="true">↗</span></a></body></html>'''

def write(path, title, description, body, cls=""):
    target = PUBLIC / path.lstrip('/') / 'index.html' if path != '/' else PUBLIC / 'index.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(layout(title, description, path, body, cls))

home = f'''
<section class="hero"><div class="hero__photo" aria-hidden="true"></div><div class="wrap hero__inner"><div class="hero__content">{kicker('BANYAN TREES · TAMPA BAY, FLORIDA')}<h1>A living landmark<br>for the <em>landscape.</em></h1><p>Young banyans delivered to your door. Mature specimen trees sourced for properties and projects that call for something extraordinary.</p><div class="actions">{button('Explore Young Trees','/young-banyan-trees/','light')}{button('Source a Specimen','/specimen-trees/','outline-light')}</div></div><p class="hero__caption">ST. PETERSBURG · TAMPA · CLEARWATER · SARASOTA</p></div></section>
<section class="intro-section section"><div class="wrap intro-grid"><div>{kicker('THE COLLECTION')}<h2>Grow the story.<br><em>Or arrive with one.</em></h2></div><p class="lead">A banyan changes the scale and feeling of a place. Begin with a young tree and watch its form take shape, or discuss a mature centerpiece for a project that needs presence now.</p></div></section>
<section class="offer-section"><div class="wrap offer-grid"><a class="offer-card offer-card--young" href="/young-banyan-trees/"><span class="offer-card__number">01 / THE BEGINNING</span><div><h3>Young trees,<br><em>delivered.</em></h3><p>Explore the young-tree collection and ask about local availability and delivery.</p><span class="text-link">Explore Young Trees <b aria-hidden="true">↗</b></span></div></a><a class="offer-card offer-card--mature" href="/specimen-trees/"><span class="offer-card__number">02 / THE CENTERPIECE</span><div><h3>A specimen<br><em>with presence.</em></h3><p>Bring us the site, the scale and the vision. We will begin with a conversation about fit.</p><span class="text-link">Explore Specimen Trees <b aria-hidden="true">↗</b></span></div></a></div></section>
<section class="section philosophy"><div class="wrap split"><figure class="image-frame">{image('The canopy and aerial roots of a mature banyan tree')}<figcaption>FORM / SCALE / PLACE</figcaption></figure><div class="split__copy">{kicker('RIGHT TREE, RIGHT PLACE')}<h2>Beauty needs room to become its own.</h2><p>Canopy, roots, coastal exposure and nearby structures deserve as much attention as appearance. A banyan is a long-term landscape decision. Start with the botanical identity and the site.</p>{button('Read the Care Guide','/banyan-tree-care-tampa-bay/','text')}</div></div></section>
<section class="section process"><div class="wrap">{section_head('THE PROCESS','A considered way to begin.','Whether you are choosing a young tree or planning a signature installation, the best result starts with a useful brief.')}<div class="steps"><article><span>01</span><h3>Tell us the setting</h3><p>Share the location, available space and the role the tree should play.</p></article><article><span>02</span><h3>Explore the right scale</h3><p>Discuss young trees or a mature specimen that suits the intended setting.</p></article><article><span>03</span><h3>Plan the next step</h3><p>Review availability, site considerations and delivery or project scope.</p></article></div></div></section>
{band('BEGIN WITH THE SITE','Give the landscape its defining moment.','Tell us where the tree will live and what you want it to become.','Start a Conversation','/consultation/')}
'''
write('/', 'Banyan Trees for Tampa Bay Landscapes', 'Explore young banyan trees and mature specimen sourcing for distinctive Tampa Bay landscapes. Based in St. Petersburg, Florida.', home, 'home')

trees = inventory.get('trees', [])
cards = []
for tree in trees:
    if not all(tree.get(k) for k in ('id','common_name','scientific_name','size','status','image')):
        raise ValueError(f"Incomplete inventory record: {tree.get('id', '?')}")
    if tree['status'] not in ('Available', 'Inquire'):
        continue
    cards.append(f'''<article class="inventory-card"><img src="{escape(tree['image'], quote=True)}" alt="{escape(tree['common_name'], quote=True)} — actual tree {escape(tree['id'], quote=True)}" loading="lazy"><div class="inventory-card__body"><span class="eyebrow">{escape(tree['status'])} · ID {escape(tree['id'])}</span><h3>{escape(tree['common_name'])}</h3><p><i>{escape(tree['scientific_name'])}</i> · {escape(tree['size'])}</p>{button('Ask About This Tree',f'/consultation/?tree={escape(tree["id"], quote=True)}','text')}</div></article>''')
inventory_html = '<div class="inventory-grid">'+''.join(cards)+'</div>' if cards else '<div class="inventory-empty"><span class="eyebrow">CURRENT COLLECTION</span><h3>Our available-tree list is being prepared.</h3><p>Ask about young banyans and the species and size you have in mind. We will confirm current availability and details directly.</p>'+button('Ask About Young Trees','/consultation/?interest=young','solid')+'</div>'
young = f'''<section class="page-hero page-hero--young"><div class="wrap page-hero__inner"><div>{kicker('01 / THE BEGINNING')}<h1>Young banyan trees,<br><em>delivered to your door.</em></h1><p class="lead">A young tree is an invitation to shape a landscape over time. Explore the collection and ask about the right species, size and local delivery for your site.</p>{button('Ask About Availability','/consultation/?interest=young')}</div><div class="page-hero__art"><span>THE NEXT<br>LANDMARK<br>STARTS HERE.</span></div></div></section>
<section class="section"><div class="wrap">{section_head('THE COLLECTION','Start with the right tree.','Each published listing will show the actual tree, botanical name, dimensions and current availability.')} {inventory_html}</div></section>
<section class="section pale"><div class="wrap split split--compact"><div>{kicker('LOCAL DELIVERY')}<h2>From the nursery<br><em>to your landscape.</em></h2></div><div><p>Tell us your ZIP code and the tree size you are considering. We will confirm delivery options, timing and any site access needs before making a commitment.</p>{button('Discuss Delivery','/consultation/?interest=young','text')}</div></div></section>
<section class="section"><div class="wrap narrow centered">{kicker('BEFORE YOU PLANT')}<h2>A beautiful beginning starts with the right site.</h2><p class="lead">Plan for the tree's eventual canopy and root space, nearby structures, coastal exposure and the care it will need while establishing.</p>{button('Read the Tampa Bay Care Guide','/banyan-tree-care-tampa-bay/')}</div></section>
{band('READY TO BEGIN?','Tell us what you have in mind.','We can discuss the species, size and space before you choose a tree.','Call About a Young Tree')}
'''
write('/young-banyan-trees/', 'Young Banyan Trees in Tampa Bay', 'Explore young banyan trees and inquire about species, size, availability and direct-to-door delivery in Tampa Bay.', young)

specimens = f'''<section class="page-hero page-hero--photo"><div class="page-hero__photo" aria-hidden="true"></div><div class="wrap page-hero__inner"><div>{kicker('02 / THE CENTERPIECE')}<h1>A centerpiece worth<br><em>designing around.</em></h1><p class="lead">For estates, signature entrances and ambitious landscape plans, a mature banyan can establish scale from day one.</p>{button('Request a Specimen Consultation','/consultation/?interest=specimen','light')}</div></div></section>
<section class="section"><div class="wrap split split--compact"><div>{kicker('SPECIMEN ACQUISITION')}<h2>Select the tree.<br>Understand the site.<br><em>Plan the arrival.</em></h2></div><p class="lead">Share the design intent and the physical realities of the property. We can discuss suitable species, available trees, access for transport and a written delivery or installation scope.</p></div></section>
<section class="section pale"><div class="wrap"><div class="steps steps--four"><article><span>01</span><h3>Brief</h3><p>Location, drawings, desired dimensions and timing.</p></article><article><span>02</span><h3>Match</h3><p>Candidate trees with botanical identity, recent photos and measurements.</p></article><article><span>03</span><h3>Feasibility</h3><p>Root space, access, utilities, equipment and approvals.</p></article><article><span>04</span><h3>Scope</h3><p>A clear proposal for transport, placement and aftercare responsibilities.</p></article></div></div></section>
<section class="section"><div class="wrap split"><figure class="image-frame image-frame--detail">{image('Architectural aerial roots and spreading branches of a mature banyan')}<figcaption>THE TREE DEFINES THE SPACE</figcaption></figure><div class="split__copy">{kicker('SITE FIT FIRST')}<h2>Presence requires a proper footprint.</h2><p>A promising tree may still be the wrong choice for a narrow courtyard, nearby foundation or exposed site. Bring us the drawings early so the tree and the property can be considered together.</p>{button('Share Your Site','/consultation/?interest=specimen','text')}</div></div></section>
{band('MATURE TREE INQUIRY','Begin with a conversation about the place.','Tell us the scale you imagine and the setting where the tree will live.','Prepare a Project Brief','/consultation/?interest=specimen')}
'''
write('/specimen-trees/', 'Mature Banyan Specimen Trees', 'Discuss mature banyan specimen sourcing for estates, builders and landscape projects across Tampa Bay.', specimens)

pros = f'''<section class="page-hero page-hero--pro"><div class="wrap page-hero__inner"><div>{kicker('TRADE & PROJECT SOURCING')}<h1>The tree that<br><em>makes the plan.</em></h1><p class="lead">For builders, developers and landscape architects designing a place around one extraordinary tree.</p>{button('Prepare a Project Brief','/consultation/?interest=professional','light')}</div><p class="page-hero__aside">ST. PETERSBURG / TAMPA / CLEARWATER / SARASOTA</p></div></section>
<section class="section"><div class="wrap split split--compact"><div>{kicker('PROJECT PARTNER')}<h2>Built around your drawings and deadline.</h2></div><div><p>Bring the species brief, desired form, dimensions, project stage and site constraints. The next step is a relevant conversation about sourcing, logistics and scope.</p>{button('Discuss a Project',f'tel:{TEL}','text')}</div></div></section>
<section class="section pale"><div class="wrap"><div class="feature-grid"><article><span>01 / SOURCING</span><h3>The right form.</h3><p>Define the character, canopy and scale the design requires.</p></article><article><span>02 / LOGISTICS</span><h3>The real constraints.</h3><p>Consider transport access, handling and placement before committing.</p></article><article><span>03 / COORDINATION</span><h3>One clear brief.</h3><p>Align the tree decision with the owner, architect and construction team.</p></article></div></div></section>
<section class="section"><div class="wrap narrow centered">{kicker('WHAT TO SEND')}<h2>The details that move a project forward.</h2><p class="lead">A site plan, desired size range, target installation window and access photographs make the first conversation more useful. Early concepts are welcome.</p>{button('Prepare a Project Brief','/consultation/?interest=professional')}</div></section>
{band('FOR PROFESSIONALS','A singular tree begins with a precise brief.','Share the vision, dimensions and project timing. We will discuss the next step.','Call to Discuss a Project')}
'''
write('/for-professionals/', 'Specimen Banyan Sourcing for Builders & Architects', 'Mature banyan sourcing conversations for Tampa Bay builders, developers and landscape architects.', pros)

care = f'''<section class="page-hero page-hero--plain"><div class="wrap page-hero__inner"><div>{kicker('FIELD NOTES / TAMPA BAY')}<h1>Growing a banyan<br><em>in Tampa Bay.</em></h1><p class="lead">The climate may be warm, but “banyan” is not one tree. Match a named species to the actual space and exposure before planting.</p></div></div></section>
<section class="section"><div class="wrap article-layout"><nav class="article-nav" aria-label="On this page"><span class="eyebrow">ON THIS PAGE</span><a href="#identity">Botanical identity</a><a href="#climate">Climate & cold</a><a href="#space">Roots & space</a><a href="#coast">Coastal exposure</a><a href="#establish">Establishment</a></nav><article class="article-copy"><section id="identity"><span>01 / IDENTITY</span><h2>Start with the botanical name.</h2><p>Trees called banyans may be different <i>Ficus</i> species with different mature forms and ecological considerations. Ask for the scientific name on any tree under consideration. Our published listings will name the exact species offered.</p></section><section id="climate"><span>02 / CLIMATE</span><h2>Check the microclimate, not just the map.</h2><p>The USDA hardiness map describes average annual extreme minimum temperatures. It does not tell the whole story of a rare freeze, wind or salt spray at a particular address. Confirm your location on the <a href="https://planthardiness.ars.usda.gov/" target="_blank" rel="noopener">official map</a> and review the species itself.</p></section><section id="space"><span>03 / SPACE</span><h2>Give canopy and roots real room.</h2><p>Large ficus can develop extensive root systems and, for some species, aerial roots. Consider foundations, paving, pools, utilities and neighboring property before choosing the planting point. A constrained site deserves a qualified local assessment.</p></section><section id="coast"><span>04 / COAST</span><h2>Look closely at exposure.</h2><p>Distance from open water, wind, salt spray, drainage and irrigation matter. A warm zone alone does not make an exposed waterfront site suitable for every banyan.</p></section><section id="establish"><span>05 / CARE</span><h2>Establish the tree deliberately.</h2><p>Plant at the correct depth and plan irrigation around tree size, soil and rainfall while the root system establishes. A large transplanted specimen needs a site-specific aftercare plan.</p></section><div class="article-note"><strong>Sources and further reading</strong><p><a href="https://plant-directory.ifas.ufl.edu/plant-directory/ficus-benghalensis/" target="_blank" rel="noopener">UF/IFAS: <i>Ficus benghalensis</i></a> · <a href="https://assessment.ifas.ufl.edu/assessments/ficus-microcarpa/" target="_blank" rel="noopener">UF/IFAS: <i>Ficus microcarpa</i> assessment</a> · <a href="https://ask.ifas.ufl.edu/publication/EP310" target="_blank" rel="noopener">UF/IFAS: choosing trees for a site</a></p></div></article></div></section>
{band('A QUESTION ABOUT YOUR SITE?','Begin with the space you have.','Tell us about nearby structures, exposure and the role the tree should play.','Call About Your Site')}
'''
write('/banyan-tree-care-tampa-bay/', 'Banyan Tree Care & Site Selection in Tampa Bay', 'A practical guide to banyan species, roots, climate, coastal exposure and establishment in Tampa Bay.', care)

about = f'''<section class="page-hero page-hero--plain"><div class="wrap page-hero__inner"><div>{kicker('OUR APPROACH')}<h1>A tree is never<br><em>just an object.</em></h1><p class="lead">A banyan becomes part of the architecture, daily life and long-term care of a property. The setting matters as much as the silhouette.</p></div></div></section>
<section class="section"><div class="wrap split"><figure class="image-frame">{image('A mature banyan tree viewed from beneath its canopy')}<figcaption>ROOTS / CANOPY / TIME</figcaption></figure><div class="split__copy">{kicker('A CONSIDERED CHOICE')}<h2>Selected for the setting.</h2><p>A beautiful tree should also be an informed choice. That means accurate species naming, honest dimensions, thoughtful placement and a practical path from selection to planting.</p><p>Choose a young tree and shape the story over time, or explore a mature specimen for a property that needs presence now.</p>{button('Explore the Collection','/young-banyan-trees/','text')}</div></div></section>
{band('TWO SCALES. ONE POINT OF VIEW.','Find the tree that belongs there.','Begin with a conversation about the place.','Start a Conversation','/consultation/')}
'''
write('/our-approach/', 'Our Approach to Banyan Trees', 'An informed approach to banyan selection, species, scale and site fit for Tampa Bay landscapes.', about)

consult = f'''<section class="page-hero page-hero--plain page-hero--short"><div class="wrap page-hero__inner"><div>{kicker('START A CONVERSATION')}<h1>Tell us about<br><em>the place.</em></h1><p class="lead">A few details will make the first call more useful. Prepare a brief here, then call us to discuss the tree and the site.</p></div></div></section>
<section class="section"><div class="wrap consultation-grid"><div><span class="eyebrow">DIRECT CONTACT</span><h2>Let's talk trees.</h2><p>For young-tree availability or a mature specimen project, call us at the number below.</p><a class="call-number" href="tel:{TEL}">{PHONE} <span aria-hidden="true">↗</span></a><p class="microcopy">The brief builder on this page runs in your browser. It does not send your information to us. Have the summary ready when you call.</p></div><form id="brief-form" class="brief-form"><fieldset><legend>01 / What are you looking for?</legend><div class="choice-row"><label><input type="radio" name="interest" value="Young tree" checked><span>A young tree</span></label><label><input type="radio" name="interest" value="Mature specimen"><span>A mature specimen</span></label><label><input type="radio" name="interest" value="Professional project"><span>A professional project</span></label></div></fieldset><div class="form-grid"><label>Project city or ZIP <input name="location" autocomplete="postal-code" placeholder="St. Petersburg, FL" required></label><label>Target timing <select name="timing"><option value="Exploring options">Exploring options</option><option value="Within 3 months">Within 3 months</option><option value="3–12 months">3–12 months</option><option value="More than 12 months">More than 12 months</option></select></label></div><label>What should the tree bring to the space? <textarea name="vision" rows="4" placeholder="A shaded courtyard, a signature entrance, a tree for an estate lawn…"></textarea></label><label>Site or access considerations <textarea name="site" rows="3" placeholder="Nearby paving, waterfront exposure, approximate planting area, truck access…"></textarea></label><button class="button button--solid" type="submit">Prepare My Brief <span aria-hidden="true">↗</span></button><p class="microcopy">Nothing is submitted online. Your summary appears below for your call.</p><div id="brief-result" class="brief-result" hidden aria-live="polite"><h3>Your conversation brief</h3><pre id="brief-summary"></pre><div class="actions"><button class="button button--outline" type="button" id="copy-brief">Copy Brief <span aria-hidden="true">↗</span></button>{button('Call Now',f'tel:{TEL}')}</div><p id="copy-status" class="microcopy" aria-live="polite"></p></div></form></div></section>
'''
write('/consultation/', 'Discuss a Banyan Tree', 'Prepare a young banyan or mature specimen project brief and call The Banyan Tree Company in St. Petersburg, Florida.', consult)

privacy = f'''<section class="page-hero page-hero--plain page-hero--short"><div class="wrap page-hero__inner"><div>{kicker('SITE INFORMATION')}<h1>Privacy.</h1><p class="lead">A straightforward note about this website's current contact flow.</p></div></div></section><section class="section"><div class="wrap narrow legal"><h2>Project brief</h2><p>The project brief on this website is prepared in your browser. It is not transmitted or stored by the website. You choose whether to copy it and share it during a phone conversation.</p><h2>Calling us</h2><p>If you call, your telephone provider and ours may process call information. We use the information you choose to share to discuss your inquiry.</p><h2>Website operation</h2><p>The site may be served through its hosting provider, which processes ordinary technical request data. External font files are requested from Google Fonts. This site currently has no online checkout, account creation or email inquiry form.</p><h2>Questions</h2><p>Call <a href="tel:{TEL}">{PHONE}</a> with a question about information shared with us. This notice may be updated as the site's features change.</p></div></section>'''
write('/privacy/', 'Privacy', 'Privacy information for visitors to The Banyan Tree Company website.', privacy)

not_found = f'''<section class="page-hero page-hero--plain page-hero--short"><div class="wrap page-hero__inner"><div>{kicker('404 / PAGE NOT FOUND')}<h1>Let's find your way back.</h1><p class="lead">The page may have moved. Begin with the collection or call us directly.</p><div class="actions">{button('Explore Young Trees','/young-banyan-trees/')}{button('Call Us',f'tel:{TEL}','outline')}</div></div></div></section>'''
(PUBLIC / '404.html').write_text(layout('Page Not Found', 'The page you are looking for is not here.', '/404.html', not_found))

routes = ['/', '/young-banyan-trees/', '/specimen-trees/', '/for-professionals/', '/banyan-tree-care-tampa-bay/', '/our-approach/', '/consultation/', '/privacy/']
(PUBLIC / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join(f'  <url><loc>{DOMAIN}{path}</loc></url>\n' for path in routes) + '</urlset>\n')
print(f'Built {len(routes)} pages; {len(cards)} confirmed inventory records')
